name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: nix shell .#ci --command bash {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: yarn build
      - run: yarn size

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: yarn build
      - run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: yarn build
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: yarn build
      - run: yarn lint:ci

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: yarn build
      - run: yarn docs:generate

  doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      # workaround b/c it's broken
      - run: yarn plugin remove @yarnpkg/plugin-version
      - run: yarn doctor packages/
