name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish, by explicit version or semver keyword."
        required: true
        default: patch

jobs:
  release-packages:
    runs-on: ubuntu-latest
    name: Release all packages
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Must be on master branch to publish packages."
          exit 1
        if: github.ref != 'refs/heads/master'
      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - name: Yarn Cache
        uses: actions/cache@v2
        with:
          path: ./.yarn
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: Install Yarn dependencies
        run: yarn install
      - run: yarn build
      - run: yarn lerna version --force-publish --no-git-tag-version --conventional-commits --yes ${{ github.event.inputs.version }}
      - name: Update Yarn deps for version bump
        run: yarn install
        env:
          CI: ""
          YARN_ENABLE_IMMUTABLE_INSTALLS: "false"
      - name: Perform Git release
        run: |
          VERSION=$(node -e "console.log(require('./lerna.json').version);")
          git config user.name "GitHub Actions"
          git config user.email github-actions@github.com
          git commit -a -m "Release v$VERSION"
          git tag "v$VERSION"
          git push origin HEAD --tags
      - name: Publish
        run: |
          echo 'npmAuthToken: "${NODE_AUTH_TOKEN}"' >> .yarnrc.yml
          git update-index --assume-unchanged .yarnrc.yml
          yarn lerna publish --no-verify-access --yes from-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
